[package]
name = "geyser-example"
version = "0.1.0"
edition = "2024"

[dependencies]
ring-shared = { path = "../ring-shared" }
clap = { version = "4", features = ["derive"] }
anchor-client = "0.32.0"
anchor-lang = "0.32.0"
tokio = { version = "1.48.0", features = ["full"] }
serde_json = "1.0"